CREATE TABLE et_payment (
    id BIGINT NOT NULL PRIMARY KEY,
    payment_number VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    order_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    provider VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    idempotency_key VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    request_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    amount BIGINT NOT NULL,
    currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    status VARCHAR(16) NOT NULL,
    provider_transaction_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    recovery_status VARCHAR(24) NOT NULL DEFAULT 'AUTO',
    attempts INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP NULL,
    lease_token VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    lease_until TIMESTAMP NULL,
    last_error VARCHAR(255) NULL,
    version INT NOT NULL DEFAULT 0,
    succeeded_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uk_et_payment_number UNIQUE(payment_number),
    CONSTRAINT uk_et_payment_order UNIQUE(order_id),
    CONSTRAINT uk_et_payment_user_idempotency UNIQUE(user_id, idempotency_key),
    CONSTRAINT uk_et_payment_provider_transaction UNIQUE(provider, provider_transaction_id),
    CONSTRAINT fk_et_payment_order FOREIGN KEY(order_id) REFERENCES et_order(id),
    CONSTRAINT ck_et_payment_amount CHECK (amount >= 0),
    CONSTRAINT ck_et_payment_currency CHECK (currency = 'CNY'),
    CONSTRAINT ck_et_payment_status CHECK (status IN ('CREATED','PROCESSING','UNKNOWN','SUCCEEDED','FAILED','CLOSED')),
    CONSTRAINT ck_et_payment_recovery CHECK (recovery_status IN ('AUTO','MANUAL_REQUIRED','NONE')),
    CONSTRAINT ck_et_payment_attempts CHECK (attempts >= 0),
    CONSTRAINT ck_et_payment_version CHECK (version >= 0),
    INDEX ix_et_payment_recovery(recovery_status, next_attempt_at, id),
    INDEX ix_et_payment_lease(lease_until)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE et_refund (
    id BIGINT NOT NULL PRIMARY KEY,
    refund_number VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    payment_id BIGINT NOT NULL,
    reason VARCHAR(32) NOT NULL,
    amount BIGINT NOT NULL,
    currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    status VARCHAR(16) NOT NULL,
    provider_refund_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    recovery_status VARCHAR(24) NOT NULL DEFAULT 'AUTO',
    attempts INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP NULL,
    lease_token VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    lease_until TIMESTAMP NULL,
    last_error VARCHAR(255) NULL,
    version INT NOT NULL DEFAULT 0,
    succeeded_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uk_et_refund_number UNIQUE(refund_number),
    CONSTRAINT uk_et_refund_payment UNIQUE(payment_id),
    CONSTRAINT uk_et_refund_provider_refund UNIQUE(provider_refund_id),
    CONSTRAINT fk_et_refund_payment FOREIGN KEY(payment_id) REFERENCES et_payment(id),
    CONSTRAINT ck_et_refund_reason CHECK (reason = 'LATE_PAYMENT'),
    CONSTRAINT ck_et_refund_amount CHECK (amount >= 0),
    CONSTRAINT ck_et_refund_currency CHECK (currency = 'CNY'),
    CONSTRAINT ck_et_refund_status CHECK (status IN ('REQUESTED','PROCESSING','UNKNOWN','SUCCEEDED','FAILED')),
    CONSTRAINT ck_et_refund_recovery CHECK (recovery_status IN ('AUTO','MANUAL_REQUIRED','NONE')),
    CONSTRAINT ck_et_refund_attempts CHECK (attempts >= 0),
    CONSTRAINT ck_et_refund_version CHECK (version >= 0),
    INDEX ix_et_refund_recovery(recovery_status, next_attempt_at, id),
    INDEX ix_et_refund_lease(lease_until)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE et_payment_callback (
    id BIGINT NOT NULL PRIMARY KEY,
    provider VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    event_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    kind VARCHAR(16) NOT NULL,
    business_number VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    payload_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    provider_result_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    order_reference VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    amount BIGINT NULL,
    currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NULL,
    result_status VARCHAR(16) NULL,
    status VARCHAR(16) NOT NULL,
    reason VARCHAR(255) NULL,
    attempts INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP NULL,
    recovery_status VARCHAR(24) NOT NULL DEFAULT 'AUTO',
    last_error VARCHAR(255) NULL,
    received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    applied_at TIMESTAMP NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uk_et_payment_callback_event UNIQUE(provider, event_id),
    CONSTRAINT ck_et_payment_callback_kind CHECK (kind IN ('PAYMENT','REFUND')),
    CONSTRAINT ck_et_payment_callback_status CHECK (status IN ('RECEIVED','APPLIED','DUPLICATE','REJECTED','UNMATCHED')),
    CONSTRAINT ck_et_payment_callback_recovery CHECK (recovery_status IN ('AUTO','MANUAL_REQUIRED','NONE')),
    CONSTRAINT ck_et_payment_callback_attempts CHECK (attempts >= 0),
    CONSTRAINT ck_et_payment_callback_amount CHECK (amount IS NULL OR amount >= 0),
    INDEX ix_et_payment_callback_recovery(recovery_status, next_attempt_at, id),
    INDEX ix_et_payment_callback_business(provider, business_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE et_payment_history (
    id BIGINT NOT NULL PRIMARY KEY,
    payment_id BIGINT NULL,
    refund_id BIGINT NULL,
    callback_id BIGINT NULL,
    action VARCHAR(48) NOT NULL,
    from_status VARCHAR(16) NULL,
    to_status VARCHAR(16) NULL,
    source VARCHAR(24) NOT NULL,
    actor_id BIGINT NULL,
    operation_key VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    request_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    detail VARCHAR(255) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_et_payment_history_payment FOREIGN KEY(payment_id) REFERENCES et_payment(id),
    CONSTRAINT fk_et_payment_history_refund FOREIGN KEY(refund_id) REFERENCES et_refund(id),
    CONSTRAINT fk_et_payment_history_callback FOREIGN KEY(callback_id) REFERENCES et_payment_callback(id),
    CONSTRAINT uk_et_payment_history_operator UNIQUE(actor_id, operation_key),
    INDEX ix_et_payment_history_payment(payment_id, created_at),
    INDEX ix_et_payment_history_refund(refund_id, created_at),
    INDEX ix_et_payment_history_callback(callback_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE sim_gateway_payment (
    payment_number VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
    order_reference VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    amount BIGINT NOT NULL,
    currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    status VARCHAR(16) NOT NULL,
    provider_transaction_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uk_sim_gateway_payment_transaction UNIQUE(provider_transaction_id),
    CONSTRAINT ck_sim_gateway_payment_amount CHECK (amount >= 0),
    CONSTRAINT ck_sim_gateway_payment_currency CHECK (currency = 'CNY'),
    CONSTRAINT ck_sim_gateway_payment_status CHECK (status IN ('PROCESSING','SUCCEEDED','FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE sim_gateway_refund (
    refund_number VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
    payment_number VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    amount BIGINT NOT NULL,
    currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    status VARCHAR(16) NOT NULL,
    provider_refund_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uk_sim_gateway_refund_payment UNIQUE(payment_number),
    CONSTRAINT uk_sim_gateway_refund_provider UNIQUE(provider_refund_id),
    CONSTRAINT fk_sim_gateway_refund_payment FOREIGN KEY(payment_number)
        REFERENCES sim_gateway_payment(payment_number),
    CONSTRAINT ck_sim_gateway_refund_amount CHECK (amount >= 0),
    CONSTRAINT ck_sim_gateway_refund_currency CHECK (currency = 'CNY'),
    CONSTRAINT ck_sim_gateway_refund_status CHECK (status IN ('PROCESSING','SUCCEEDED','FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
